import { CountryAttributeProps } from "@/data/PropTypes";

export const countryAttributes = <CountryAttributeProps[]>[
  {
    name: "United States",
    code: "US",
    emoji: "Ã°Å¸â€¡ÂºÃ°Å¸â€¡Â¸",
    e164_country_code: "+001",
    slug: "united-states",
  },
  {
    name: "Afghanistan",
    code: "AF",
    emoji: "Ã°Å¸â€¡Â¦Ã°Å¸â€¡Â«",
    e164_country_code: "+093",
    slug: "afghanistan",
  },
  {
    name: "Albania",
    code: "AL",
    emoji: "Ã°Å¸â€¡Â¦Ã°Å¸â€¡Â±",
    e164_country_code: "+355",
    slug: "albania",
  },
  {
    name: "Andorra",
    code: "AD",
    emoji: "Ã°Å¸â€¡Â¦Ã°Å¸â€¡Â©",
    e164_country_code: "+376",
    slug: "andorra",
  },
  {
    name: "Angola",
    code: "AO",
    emoji: "Ã°Å¸â€¡Â¦Ã°Å¸â€¡Â´",
    e164_country_code: "+244",
    slug: "angola",
  },
  {
    name: "Anguilla",
    code: "AI",
    emoji: "Ã°Å¸â€¡Â¦Ã°Å¸â€¡Â®",
    e164_country_code: "+001",
    slug: "anguilla",
  },
  {
    name: "Antarctica",
    code: "AQ",
    emoji: "Ã°Å¸â€¡Â¦Ã°Å¸â€¡Â¶",
    e164_country_code: "+672",
    slug: "antarctica",
  },
  {
    name: "Antigua & Barbuda",
    code: "AG",
    emoji: "Ã°Å¸â€¡Â¦Ã°Å¸â€¡Â¬",
    e164_country_code: "+001",
    slug: "antigua-and-barbuda",
  },
  {
    name: "Argentina",
    code: "AR",
    emoji: "Ã°Å¸â€¡Â¦Ã°Å¸â€¡Â·",
    e164_country_code: "+054",
    slug: "argentina",
  },
  {
    name: "Armenia",
    code: "AM",
    emoji: "Ã°Å¸â€¡Â¦Ã°Å¸â€¡Â²",
    e164_country_code: "+374",
    slug: "armenia",
  },
  {
    name: "Aruba",
    code: "AW",
    emoji: "Ã°Å¸â€¡Â¦Ã°Å¸â€¡Â¼",
    e164_country_code: "+297",
    slug: "aruba",
  },
  {
    name: "Ascension Island",
    code: "AC",
    emoji: "Ã°Å¸â€¡Â¦Ã°Å¸â€¡Â¨",
    e164_country_code: "+247",
    slug: "ascension-island",
  },
  {
    name: "Australia",
    code: "AU",
    emoji: "Ã°Å¸â€¡Â¦Ã°Å¸â€¡Âº",
    e164_country_code: "+061",
    slug: "australia",
  },
  {
    name: "Austria",
    code: "AT",
    emoji: "Ã°Å¸â€¡Â¦Ã°Å¸â€¡Â¹",
    e164_country_code: "+043",
    slug: "austria",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    emoji: "Ã°Å¸â€¡Â¦Ã°Å¸â€¡Â¿",
    e164_country_code: "+994",
    slug: "azerbaijan",
  },
  {
    name: "Bahamas",
    code: "BS",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â¸",
    e164_country_code: "+001",
    slug: "bahamas",
  },
  {
    name: "Bahrain",
    code: "BH",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â­",
    e164_country_code: "+973",
    slug: "bahrain",
  },
  {
    name: "Bangladesh",
    code: "BD",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â©",
    e164_country_code: "+880",
    slug: "bangladesh",
  },
  {
    name: "Barbados",
    code: "BB",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â§",
    e164_country_code: "+001",
    slug: "barbados",
  },
  {
    name: "Belarus",
    code: "BY",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â¾",
    e164_country_code: "+375",
    slug: "belarus",
  },
  {
    name: "Belgium",
    code: "BE",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Âª",
    e164_country_code: "+032",
    slug: "belgium",
  },
  {
    name: "Belize",
    code: "BZ",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â¿",
    e164_country_code: "+501",
    slug: "belize",
  },
  {
    name: "Benin",
    code: "BJ",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â¯",
    e164_country_code: "+229",
    slug: "benin",
  },
  {
    name: "Bermuda",
    code: "BM",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â²",
    e164_country_code: "+001",
    slug: "bermuda",
  },
  {
    name: "Bhutan",
    code: "BT",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â¹",
    e164_country_code: "+975",
    slug: "bhutan",
  },
  {
    name: "Bolivia",
    code: "BO",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â´",
    e164_country_code: "+591",
    slug: "bolivia",
  },
  {
    name: "Bosnia & Herzegovina",
    code: "BA",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â¦",
    e164_country_code: "+387",
    slug: "bosnia-and-herzegovina",
  },
  {
    name: "Botswana",
    code: "BW",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â¼",
    e164_country_code: "+267",
    slug: "botswana",
  },
  {
    name: "Brazil",
    code: "BR",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â·",
    e164_country_code: "+055",
    slug: "brazil",
  },
  {
    name: "British Indian Ocean Territory",
    code: "IO",
    emoji: "Ã°Å¸â€¡Â®Ã°Å¸â€¡Â´",
    e164_country_code: "+246",
    slug: "british-indian-ocean-territory",
  },
  {
    name: "Brunei",
    code: "BN",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â³",
    e164_country_code: "+673",
    slug: "brunei",
  },
  {
    name: "Bulgaria",
    code: "BG",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â¬",
    e164_country_code: "+359",
    slug: "bulgaria",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â«",
    e164_country_code: "+226",
    slug: "burkina-faso",
  },
  {
    name: "Burundi",
    code: "BI",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â®",
    e164_country_code: "+257",
    slug: "burundi",
  },
  {
    name: "Cabo Verde",
    code: "CV",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â»",
    e164_country_code: "+238",
    slug: "cabo-verde",
  },
  {
    name: "Cambodia",
    code: "KH",
    emoji: "Ã°Å¸â€¡Â°Ã°Å¸â€¡Â­",
    e164_country_code: "+855",
    slug: "cambodia",
  },
  {
    name: "Cameroon",
    code: "CM",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â²",
    e164_country_code: "+237",
    slug: "cameroon",
  },
  {
    name: "Canada",
    code: "CA",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â¦",
    e164_country_code: "+001",
    slug: "canada",
  },
  {
    name: "Cayman Islands",
    code: "KY",
    emoji: "Ã°Å¸â€¡Â°Ã°Å¸â€¡Â¾",
    e164_country_code: "+001",
    slug: "cayman-islands",
  },
  {
    name: "Central African Republic",
    code: "CF",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â«",
    e164_country_code: "+236",
    slug: "central-african-republic",
  },
  {
    name: "Chad",
    code: "TD",
    emoji: "Ã°Å¸â€¡Â¹Ã°Å¸â€¡Â©",
    e164_country_code: "+235",
    slug: "chad",
  },
  {
    name: "Chile",
    code: "CL",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â±",
    e164_country_code: "+056",
    slug: "chile",
  },
  {
    name: "China",
    code: "CN",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â³",
    e164_country_code: "+086",
    slug: "china",
  },
  {
    name: "Christmas Island",
    code: "CX",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â½",
    e164_country_code: "+061",
    slug: "christmas-island",
  },
  {
    name: "Cocos (Keeling) Islands",
    code: "CC",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â¨",
    e164_country_code: "+061",
    slug: "cocos-(keeling)-islands",
  },
  {
    name: "Colombia",
    code: "CO",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â´",
    e164_country_code: "+057",
    slug: "colombia",
  },
  {
    name: "Comoros",
    code: "KM",
    emoji: "Ã°Å¸â€¡Â°Ã°Å¸â€¡Â²",
    e164_country_code: "+269",
    slug: "comoros",
  },
  {
    name: "Congo - Brazzaville",
    code: "CG",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â¬",
    e164_country_code: "+242",
    slug: "congo-brazzaville",
  },
  {
    name: "Congo - Kinshasa",
    code: "CD",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â©",
    e164_country_code: "+243",
    slug: "congo-kinshasa",
  },
  {
    name: "Cook Islands",
    code: "CK",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â°",
    e164_country_code: "+682",
    slug: "cook-islands",
  },
  {
    name: "Costa Rica",
    code: "CR",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â·",
    e164_country_code: "+506",
    slug: "costa-rica",
  },
  {
    name: "Croatia",
    code: "HR",
    emoji: "Ã°Å¸â€¡Â­Ã°Å¸â€¡Â·",
    e164_country_code: "+385",
    slug: "croatia",
  },
  {
    name: "Cuba",
    code: "CU",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Âº",
    e164_country_code: "+053",
    slug: "cuba",
  },
  {
    name: "CuraÃƒÂ§ao",
    code: "CW",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â¼",
    e164_country_code: "+599",
    slug: "curacao",
  },
  {
    name: "Cyprus",
    code: "CY",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â¾",
    e164_country_code: "+357",
    slug: "cyprus",
  },
  {
    name: "Czechia",
    code: "CZ",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â¿",
    e164_country_code: "+420",
    slug: "czechia",
  },
  {
    name: "CÃƒÂ´te dÃ¢â‚¬â„¢Ivoire",
    code: "CI",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â®",
    e164_country_code: "+225",
    slug: "cote-d'ivoire",
  },
  {
    name: "Denmark",
    code: "DK",
    emoji: "Ã°Å¸â€¡Â©Ã°Å¸â€¡Â°",
    e164_country_code: "+045",
    slug: "denmark",
  },
  {
    name: "Djibouti",
    code: "DJ",
    emoji: "Ã°Å¸â€¡Â©Ã°Å¸â€¡Â¯",
    e164_country_code: "+253",
    slug: "djibouti",
  },
  {
    name: "Dominica",
    code: "DM",
    emoji: "Ã°Å¸â€¡Â©Ã°Å¸â€¡Â²",
    e164_country_code: "+001",
    slug: "dominica",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    emoji: "Ã°Å¸â€¡Â©Ã°Å¸â€¡Â´",
    e164_country_code: "+001",
    slug: "dominican-republic",
  },
  {
    name: "Ecuador",
    code: "EC",
    emoji: "Ã°Å¸â€¡ÂªÃ°Å¸â€¡Â¨",
    e164_country_code: "+593",
    slug: "ecuador",
  },
  {
    name: "Egypt",
    code: "EG",
    emoji: "Ã°Å¸â€¡ÂªÃ°Å¸â€¡Â¬",
    e164_country_code: "+020",
    slug: "egypt",
  },
  {
    name: "El Salvador",
    code: "SV",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â»",
    e164_country_code: "+503",
    slug: "el-salvador",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Â¶",
    e164_country_code: "+240",
    slug: "equatorial-guinea",
  },
  {
    name: "Eritrea",
    code: "ER",
    emoji: "Ã°Å¸â€¡ÂªÃ°Å¸â€¡Â·",
    e164_country_code: "+291",
    slug: "eritrea",
  },
  {
    name: "Estonia",
    code: "EE",
    emoji: "Ã°Å¸â€¡ÂªÃ°Å¸â€¡Âª",
    e164_country_code: "+372",
    slug: "estonia",
  },
  {
    name: "Eswatini",
    code: "SZ",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â¿",
    e164_country_code: "+268",
    slug: "eswatini",
  },
  {
    name: "Ethiopia",
    code: "ET",
    emoji: "Ã°Å¸â€¡ÂªÃ°Å¸â€¡Â¹",
    e164_country_code: "+251",
    slug: "ethiopia",
  },
  {
    name: "Falkland Islands",
    code: "FK",
    emoji: "Ã°Å¸â€¡Â«Ã°Å¸â€¡Â°",
    e164_country_code: "+500",
    slug: "falkland-islands",
  },
  {
    name: "Faroe Islands",
    code: "FO",
    emoji: "Ã°Å¸â€¡Â«Ã°Å¸â€¡Â´",
    e164_country_code: "+298",
    slug: "faroe-islands",
  },
  {
    name: "Fiji",
    code: "FJ",
    emoji: "Ã°Å¸â€¡Â«Ã°Å¸â€¡Â¯",
    e164_country_code: "+679",
    slug: "fiji",
  },
  {
    name: "Finland",
    code: "FI",
    emoji: "Ã°Å¸â€¡Â«Ã°Å¸â€¡Â®",
    e164_country_code: "+358",
    slug: "finland",
  },
  {
    name: "France",
    code: "FR",
    emoji: "Ã°Å¸â€¡Â«Ã°Å¸â€¡Â·",
    e164_country_code: "+033",
    slug: "france",
  },
  {
    name: "French Guiana",
    code: "GF",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Â«",
    e164_country_code: "+594",
    slug: "french-guiana",
  },
  {
    name: "French Polynesia",
    code: "PF",
    emoji: "Ã°Å¸â€¡ÂµÃ°Å¸â€¡Â«",
    e164_country_code: "+689",
    slug: "french-polynesia",
  },
  {
    name: "French Southern Territories",
    code: "TF",
    emoji: "Ã°Å¸â€¡Â¹Ã°Å¸â€¡Â«",
    e164_country_code: "+262",
    slug: "french-southern-territories",
  },
  {
    name: "Gabon",
    code: "GA",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Â¦",
    e164_country_code: "+241",
    slug: "gabon",
  },
  {
    name: "Gambia",
    code: "GM",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Â²",
    e164_country_code: "+220",
    slug: "gambia",
  },
  {
    name: "Georgia",
    code: "GE",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Âª",
    e164_country_code: "+995",
    slug: "georgia",
  },
  {
    name: "Germany",
    code: "DE",
    emoji: "Ã°Å¸â€¡Â©Ã°Å¸â€¡Âª",
    e164_country_code: "+049",
    slug: "germany",
  },
  {
    name: "Ghana",
    code: "GH",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Â­",
    e164_country_code: "+233",
    slug: "ghana",
  },
  {
    name: "Gibraltar",
    code: "GI",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Â®",
    e164_country_code: "+350",
    slug: "gibraltar",
  },
  {
    name: "Greece",
    code: "GR",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Â·",
    e164_country_code: "+030",
    slug: "greece",
  },
  {
    name: "Greenland",
    code: "GL",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Â±",
    e164_country_code: "+299",
    slug: "greenland",
  },
  {
    name: "Grenada",
    code: "GD",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Â©",
    e164_country_code: "+001",
    slug: "grenada",
  },
  {
    name: "Guadeloupe",
    code: "GP",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Âµ",
    e164_country_code: "+590",
    slug: "guadeloupe",
  },
  {
    name: "Guam",
    code: "GU",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Âº",
    e164_country_code: "+001",
    slug: "guam",
  },
  {
    name: "Guatemala",
    code: "GT",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Â¹",
    e164_country_code: "+502",
    slug: "guatemala",
  },
  {
    name: "Guernsey",
    code: "GG",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Â¬",
    e164_country_code: "+044",
    slug: "guernsey",
  },
  {
    name: "Guinea",
    code: "GN",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Â³",
    e164_country_code: "+224",
    slug: "guinea",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Â¼",
    e164_country_code: "+245",
    slug: "guinea-bissau",
  },
  {
    name: "Guyana",
    code: "GY",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Â¾",
    e164_country_code: "+592",
    slug: "guyana",
  },
  {
    name: "Haiti",
    code: "HT",
    emoji: "Ã°Å¸â€¡Â­Ã°Å¸â€¡Â¹",
    e164_country_code: "+509",
    slug: "haiti",
  },
  {
    name: "Heard & McDonald Islands",
    code: "HM",
    emoji: "Ã°Å¸â€¡Â­Ã°Å¸â€¡Â²",
    e164_country_code: "+672",
    slug: "heard-and-mcdonald-islands",
  },
  {
    name: "Honduras",
    code: "HN",
    emoji: "Ã°Å¸â€¡Â­Ã°Å¸â€¡Â³",
    e164_country_code: "+504",
    slug: "honduras",
  },
  {
    name: "Hong Kong SAR China",
    code: "HK",
    emoji: "Ã°Å¸â€¡Â­Ã°Å¸â€¡Â°",
    e164_country_code: "+852",
    slug: "hong-kong-sar-china",
  },
  {
    name: "Hungary",
    code: "HU",
    emoji: "Ã°Å¸â€¡Â­Ã°Å¸â€¡Âº",
    e164_country_code: "+036",
    slug: "hungary",
  },
  {
    name: "Iceland",
    code: "IS",
    emoji: "Ã°Å¸â€¡Â®Ã°Å¸â€¡Â¸",
    e164_country_code: "+354",
    slug: "iceland",
  },
  {
    name: "India",
    code: "IN",
    emoji: "Ã°Å¸â€¡Â®Ã°Å¸â€¡Â³",
    e164_country_code: "+091",
    slug: "india",
  },
  {
    name: "Indonesia",
    code: "ID",
    emoji: "Ã°Å¸â€¡Â®Ã°Å¸â€¡Â©",
    e164_country_code: "+062",
    slug: "indonesia",
  },
  {
    name: "Iran",
    code: "IR",
    emoji: "Ã°Å¸â€¡Â®Ã°Å¸â€¡Â·",
    e164_country_code: "+098",
    slug: "iran",
  },
  {
    name: "Iraq",
    code: "IQ",
    emoji: "Ã°Å¸â€¡Â®Ã°Å¸â€¡Â¶",
    e164_country_code: "+964",
    slug: "iraq",
  },
  {
    name: "Ireland",
    code: "IE",
    emoji: "Ã°Å¸â€¡Â®Ã°Å¸â€¡Âª",
    e164_country_code: "+353",
    slug: "ireland",
  },
  {
    name: "Isle of Man",
    code: "IM",
    emoji: "Ã°Å¸â€¡Â®Ã°Å¸â€¡Â²",
    e164_country_code: "+044",
    slug: "isle-of-man",
  },
  {
    name: "Israel",
    code: "IL",
    emoji: "Ã°Å¸â€¡Â®Ã°Å¸â€¡Â±",
    e164_country_code: "+972",
    slug: "israel",
  },
  {
    name: "Italy",
    code: "IT",
    emoji: "Ã°Å¸â€¡Â®Ã°Å¸â€¡Â¹",
    e164_country_code: "+039",
    slug: "italy",
  },
  {
    name: "Jamaica",
    code: "JM",
    emoji: "Ã°Å¸â€¡Â¯Ã°Å¸â€¡Â²",
    e164_country_code: "+001",
    slug: "jamaica",
  },
  {
    name: "Japan",
    code: "JP",
    emoji: "Ã°Å¸â€¡Â¯Ã°Å¸â€¡Âµ",
    e164_country_code: "+081",
    slug: "japan",
  },
  {
    name: "Jersey",
    code: "JE",
    emoji: "Ã°Å¸â€¡Â¯Ã°Å¸â€¡Âª",
    e164_country_code: "+044",
    slug: "jersey",
  },
  {
    name: "Jordan",
    code: "JO",
    emoji: "Ã°Å¸â€¡Â¯Ã°Å¸â€¡Â´",
    e164_country_code: "+962",
    slug: "jordan",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    emoji: "Ã°Å¸â€¡Â°Ã°Å¸â€¡Â¿",
    e164_country_code: "+007",
    slug: "kazakhstan",
  },
  {
    name: "Kenya",
    code: "KE",
    emoji: "Ã°Å¸â€¡Â°Ã°Å¸â€¡Âª",
    e164_country_code: "+254",
    slug: "kenya",
  },
  {
    name: "Kiribati",
    code: "KI",
    emoji: "Ã°Å¸â€¡Â°Ã°Å¸â€¡Â®",
    e164_country_code: "+686",
    slug: "kiribati",
  },
  {
    name: "Kosovo",
    code: "XK",
    emoji: "Ã°Å¸â€¡Â½Ã°Å¸â€¡Â°",
    e164_country_code: "+383",
    slug: "kosovo",
  },
  {
    name: "Kuwait",
    code: "KW",
    emoji: "Ã°Å¸â€¡Â°Ã°Å¸â€¡Â¼",
    e164_country_code: "+965",
    slug: "kuwait",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    emoji: "Ã°Å¸â€¡Â°Ã°Å¸â€¡Â¬",
    e164_country_code: "+996",
    slug: "kyrgyzstan",
  },
  {
    name: "Laos",
    code: "LA",
    emoji: "Ã°Å¸â€¡Â±Ã°Å¸â€¡Â¦",
    e164_country_code: "+856",
    slug: "laos",
  },
  {
    name: "Latvia",
    code: "LV",
    emoji: "Ã°Å¸â€¡Â±Ã°Å¸â€¡Â»",
    e164_country_code: "+371",
    slug: "latvia",
  },
  {
    name: "Lebanon",
    code: "LB",
    emoji: "Ã°Å¸â€¡Â±Ã°Å¸â€¡Â§",
    e164_country_code: "+961",
    slug: "lebanon",
  },
  {
    name: "Lesotho",
    code: "LS",
    emoji: "Ã°Å¸â€¡Â±Ã°Å¸â€¡Â¸",
    e164_country_code: "+266",
    slug: "lesotho",
  },
  {
    name: "Liberia",
    code: "LR",
    emoji: "Ã°Å¸â€¡Â±Ã°Å¸â€¡Â·",
    e164_country_code: "+231",
    slug: "liberia",
  },
  {
    name: "Libya",
    code: "LY",
    emoji: "Ã°Å¸â€¡Â±Ã°Å¸â€¡Â¾",
    e164_country_code: "+218",
    slug: "libya",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    emoji: "Ã°Å¸â€¡Â±Ã°Å¸â€¡Â®",
    e164_country_code: "+423",
    slug: "liechtenstein",
  },
  {
    name: "Lithuania",
    code: "LT",
    emoji: "Ã°Å¸â€¡Â±Ã°Å¸â€¡Â¹",
    e164_country_code: "+370",
    slug: "lithuania",
  },
  {
    name: "Luxembourg",
    code: "LU",
    emoji: "Ã°Å¸â€¡Â±Ã°Å¸â€¡Âº",
    e164_country_code: "+352",
    slug: "luxembourg",
  },
  {
    name: "Macao SAR China",
    code: "MO",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â´",
    e164_country_code: "+853",
    slug: "macao-sar-china",
  },
  {
    name: "Madagascar",
    code: "MG",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â¬",
    e164_country_code: "+261",
    slug: "madagascar",
  },
  {
    name: "Malawi",
    code: "MW",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â¼",
    e164_country_code: "+265",
    slug: "malawi",
  },
  {
    name: "Malaysia",
    code: "MY",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â¾",
    e164_country_code: "+060",
    slug: "malaysia",
  },
  {
    name: "Maldives",
    code: "MV",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â»",
    e164_country_code: "+960",
    slug: "maldives",
  },
  {
    name: "Mali",
    code: "ML",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â±",
    e164_country_code: "+223",
    slug: "mali",
  },
  {
    name: "Malta",
    code: "MT",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â¹",
    e164_country_code: "+356",
    slug: "malta",
  },
  {
    name: "Marshall Islands",
    code: "MH",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â­",
    e164_country_code: "+692",
    slug: "marshall-islands",
  },
  {
    name: "Martinique",
    code: "MQ",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â¶",
    e164_country_code: "+596",
    slug: "martinique",
  },
  {
    name: "Mauritania",
    code: "MR",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â·",
    e164_country_code: "+222",
    slug: "mauritania",
  },
  {
    name: "Mauritius",
    code: "MU",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Âº",
    e164_country_code: "+230",
    slug: "mauritius",
  },
  {
    name: "Mayotte",
    code: "YT",
    emoji: "Ã°Å¸â€¡Â¾Ã°Å¸â€¡Â¹",
    e164_country_code: "+262",
    slug: "mayotte",
  },
  {
    name: "Mexico",
    code: "MX",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â½",
    e164_country_code: "+052",
    slug: "mexico",
  },
  {
    name: "Micronesia",
    code: "FM",
    emoji: "Ã°Å¸â€¡Â«Ã°Å¸â€¡Â²",
    e164_country_code: "+691",
    slug: "micronesia",
  },
  {
    name: "Moldova",
    code: "MD",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â©",
    e164_country_code: "+373",
    slug: "moldova",
  },
  {
    name: "Monaco",
    code: "MC",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â¨",
    e164_country_code: "+377",
    slug: "monaco",
  },
  {
    name: "Mongolia",
    code: "MN",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â³",
    e164_country_code: "+976",
    slug: "mongolia",
  },
  {
    name: "Montenegro",
    code: "ME",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Âª",
    e164_country_code: "+382",
    slug: "montenegro",
  },
  {
    name: "Montserrat",
    code: "MS",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â¸",
    e164_country_code: "+001",
    slug: "montserrat",
  },
  {
    name: "Morocco",
    code: "MA",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â¦",
    e164_country_code: "+212",
    slug: "morocco",
  },
  {
    name: "Mozambique",
    code: "MZ",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â¿",
    e164_country_code: "+258",
    slug: "mozambique",
  },
  {
    name: "Myanmar (Burma)",
    code: "MM",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â²",
    e164_country_code: "+095",
    slug: "myanmar-(burma)",
  },
  {
    name: "Namibia",
    code: "NA",
    emoji: "Ã°Å¸â€¡Â³Ã°Å¸â€¡Â¦",
    e164_country_code: "+264",
    slug: "namibia",
  },
  {
    name: "Nauru",
    code: "NR",
    emoji: "Ã°Å¸â€¡Â³Ã°Å¸â€¡Â·",
    e164_country_code: "+674",
    slug: "nauru",
  },
  {
    name: "Nepal",
    code: "NP",
    emoji: "Ã°Å¸â€¡Â³Ã°Å¸â€¡Âµ",
    e164_country_code: "+977",
    slug: "nepal",
  },
  {
    name: "Netherlands",
    code: "NL",
    emoji: "Ã°Å¸â€¡Â³Ã°Å¸â€¡Â±",
    e164_country_code: "+031",
    slug: "netherlands",
  },
  {
    name: "New Caledonia",
    code: "NC",
    emoji: "Ã°Å¸â€¡Â³Ã°Å¸â€¡Â¨",
    e164_country_code: "+687",
    slug: "new-caledonia",
  },
  {
    name: "New Zealand",
    code: "NZ",
    emoji: "Ã°Å¸â€¡Â³Ã°Å¸â€¡Â¿",
    e164_country_code: "+064",
    slug: "new-zealand",
  },
  {
    name: "Nicaragua",
    code: "NI",
    emoji: "Ã°Å¸â€¡Â³Ã°Å¸â€¡Â®",
    e164_country_code: "+505",
    slug: "nicaragua",
  },
  {
    name: "Niger",
    code: "NE",
    emoji: "Ã°Å¸â€¡Â³Ã°Å¸â€¡Âª",
    e164_country_code: "+227",
    slug: "niger",
  },
  {
    name: "Nigeria",
    code: "NG",
    emoji: "Ã°Å¸â€¡Â³Ã°Å¸â€¡Â¬",
    e164_country_code: "+234",
    slug: "nigeria",
  },
  {
    name: "Niue",
    code: "NU",
    emoji: "Ã°Å¸â€¡Â³Ã°Å¸â€¡Âº",
    e164_country_code: "+683",
    slug: "niue",
  },
  {
    name: "Norfolk Island",
    code: "NF",
    emoji: "Ã°Å¸â€¡Â³Ã°Å¸â€¡Â«",
    e164_country_code: "+672",
    slug: "norfolk-island",
  },
  {
    name: "North Korea",
    code: "KP",
    emoji: "Ã°Å¸â€¡Â°Ã°Å¸â€¡Âµ",
    e164_country_code: "+850",
    slug: "north-korea",
  },
  {
    name: "Northern Mariana Islands",
    code: "MP",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Âµ",
    e164_country_code: "+001",
    slug: "northern-mariana-islands",
  },
  {
    name: "Norway",
    code: "NO",
    emoji: "Ã°Å¸â€¡Â³Ã°Å¸â€¡Â´",
    e164_country_code: "+047",
    slug: "norway",
  },
  {
    name: "Oman",
    code: "OM",
    emoji: "Ã°Å¸â€¡Â´Ã°Å¸â€¡Â²",
    e164_country_code: "+968",
    slug: "oman",
  },
  {
    name: "Pakistan",
    code: "PK",
    emoji: "Ã°Å¸â€¡ÂµÃ°Å¸â€¡Â°",
    e164_country_code: "+092",
    slug: "pakistan",
  },
  {
    name: "Palau",
    code: "PW",
    emoji: "Ã°Å¸â€¡ÂµÃ°Å¸â€¡Â¼",
    e164_country_code: "+680",
    slug: "palau",
  },
  {
    name: "Palestinian Territories",
    code: "PS",
    emoji: "Ã°Å¸â€¡ÂµÃ°Å¸â€¡Â¸",
    e164_country_code: "+970",
    slug: "palestinian-territories",
  },
  {
    name: "Panama",
    code: "PA",
    emoji: "Ã°Å¸â€¡ÂµÃ°Å¸â€¡Â¦",
    e164_country_code: "+507",
    slug: "panama",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    emoji: "Ã°Å¸â€¡ÂµÃ°Å¸â€¡Â¬",
    e164_country_code: "+675",
    slug: "papua-new-guinea",
  },
  {
    name: "Paraguay",
    code: "PY",
    emoji: "Ã°Å¸â€¡ÂµÃ°Å¸â€¡Â¾",
    e164_country_code: "+595",
    slug: "paraguay",
  },
  {
    name: "Peru",
    code: "PE",
    emoji: "Ã°Å¸â€¡ÂµÃ°Å¸â€¡Âª",
    e164_country_code: "+051",
    slug: "peru",
  },
  {
    name: "Philippines",
    code: "PH",
    emoji: "Ã°Å¸â€¡ÂµÃ°Å¸â€¡Â­",
    e164_country_code: "+063",
    slug: "philippines",
  },
  {
    name: "Pitcairn Islands",
    code: "PN",
    emoji: "Ã°Å¸â€¡ÂµÃ°Å¸â€¡Â³",
    e164_country_code: "+064",
    slug: "pitcairn-islands",
  },
  {
    name: "Poland",
    code: "PL",
    emoji: "Ã°Å¸â€¡ÂµÃ°Å¸â€¡Â±",
    e164_country_code: "+048",
    slug: "poland",
  },
  {
    name: "Portugal",
    code: "PT",
    emoji: "Ã°Å¸â€¡ÂµÃ°Å¸â€¡Â¹",
    e164_country_code: "+351",
    slug: "portugal",
  },
  {
    name: "Puerto Rico",
    code: "PR",
    emoji: "Ã°Å¸â€¡ÂµÃ°Å¸â€¡Â·",
    e164_country_code: "+001",
    slug: "puerto-rico",
  },
  {
    name: "Qatar",
    code: "QA",
    emoji: "Ã°Å¸â€¡Â¶Ã°Å¸â€¡Â¦",
    e164_country_code: "+974",
    slug: "qatar",
  },
  {
    name: "RÃƒÂ©union",
    code: "RE",
    emoji: "Ã°Å¸â€¡Â·Ã°Å¸â€¡Âª",
    e164_country_code: "+262",
    slug: "reunion",
  },
  {
    name: "Romania",
    code: "RO",
    emoji: "Ã°Å¸â€¡Â·Ã°Å¸â€¡Â´",
    e164_country_code: "+040",
    slug: "romania",
  },
  {
    name: "Russia",
    code: "RU",
    emoji: "Ã°Å¸â€¡Â·Ã°Å¸â€¡Âº",
    e164_country_code: "+007",
    slug: "russia",
  },
  {
    name: "Rwanda",
    code: "RW",
    emoji: "Ã°Å¸â€¡Â·Ã°Å¸â€¡Â¼",
    e164_country_code: "+250",
    slug: "rwanda",
  },
  {
    name: "Saint BarthÃƒÂ©lemy",
    code: "BL",
    emoji: "Ã°Å¸â€¡Â§Ã°Å¸â€¡Â±",
    e164_country_code: "+590",
    slug: "saint-barthelemy",
  },
  {
    name: "Saint Helena",
    code: "SH",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â­",
    e164_country_code: "+290",
    slug: "saint-helena",
  },
  {
    name: "Saint Kitts & Nevis",
    code: "KN",
    emoji: "Ã°Å¸â€¡Â°Ã°Å¸â€¡Â³",
    e164_country_code: "+001",
    slug: "saint-kitts-and-nevis",
  },
  {
    name: "Saint Lucia",
    code: "LC",
    emoji: "Ã°Å¸â€¡Â±Ã°Å¸â€¡Â¨",
    e164_country_code: "+001",
    slug: "saint-lucia",
  },
  {
    name: "Saint Martin",
    code: "MF",
    emoji: "Ã°Å¸â€¡Â²Ã°Å¸â€¡Â«",
    e164_country_code: "+590",
    slug: "saint-martin",
  },
  {
    name: "Saint Pierre & Miquelon",
    code: "PM",
    emoji: "Ã°Å¸â€¡ÂµÃ°Å¸â€¡Â²",
    e164_country_code: "+508",
    slug: "saint-pierre-and-miquelon",
  },
  {
    name: "Samoa",
    code: "WS",
    emoji: "Ã°Å¸â€¡Â¼Ã°Å¸â€¡Â¸",
    e164_country_code: "+685",
    slug: "samoa",
  },
  {
    name: "San Marino",
    code: "SM",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â²",
    e164_country_code: "+378",
    slug: "san-marino",
  },
  {
    name: "Sao Tome & Principe",
    code: "ST",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â¹",
    e164_country_code: "+239",
    slug: "sao-tome-and-principe",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â¦",
    e164_country_code: "+966",
    slug: "saudi-arabia",
  },
  {
    name: "Senegal",
    code: "SN",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â³",
    e164_country_code: "+221",
    slug: "senegal",
  },
  {
    name: "Serbia",
    code: "RS",
    emoji: "Ã°Å¸â€¡Â·Ã°Å¸â€¡Â¸",
    e164_country_code: "+381",
    slug: "serbia",
  },
  {
    name: "Seychelles",
    code: "SC",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â¨",
    e164_country_code: "+248",
    slug: "seychelles",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â±",
    e164_country_code: "+232",
    slug: "sierra-leone",
  },
  {
    name: "Singapore",
    code: "SG",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â¬",
    e164_country_code: "+065",
    slug: "singapore",
  },
  {
    name: "Sint Maarten",
    code: "SX",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â½",
    e164_country_code: "+001",
    slug: "sint-maarten",
  },
  {
    name: "Slovakia",
    code: "SK",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â°",
    e164_country_code: "+421",
    slug: "slovakia",
  },
  {
    name: "Slovenia",
    code: "SI",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â®",
    e164_country_code: "+386",
    slug: "slovenia",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â§",
    e164_country_code: "+677",
    slug: "solomon-islands",
  },
  {
    name: "Somalia",
    code: "SO",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â´",
    e164_country_code: "+252",
    slug: "somalia",
  },
  {
    name: "South Africa",
    code: "ZA",
    emoji: "Ã°Å¸â€¡Â¿Ã°Å¸â€¡Â¦",
    e164_country_code: "+027",
    slug: "south-africa",
  },
  {
    name: "South Georgia & South Sandwich Islands",
    code: "GS",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Â¸",
    e164_country_code: "+500",
    slug: "south-georgia-and-south-sandwich-islands",
  },
  {
    name: "South Korea",
    code: "KR",
    emoji: "Ã°Å¸â€¡Â°Ã°Å¸â€¡Â·",
    e164_country_code: "+082",
    slug: "south-korea",
  },
  {
    name: "South Sudan",
    code: "SS",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â¸",
    e164_country_code: "+211",
    slug: "south-sudan",
  },
  {
    name: "Spain",
    code: "ES",
    emoji: "Ã°Å¸â€¡ÂªÃ°Å¸â€¡Â¸",
    e164_country_code: "+034",
    slug: "spain",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    emoji: "Ã°Å¸â€¡Â±Ã°Å¸â€¡Â°",
    e164_country_code: "+094",
    slug: "sri-lanka",
  },
  {
    name: "Sudan",
    code: "SD",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â©",
    e164_country_code: "+249",
    slug: "sudan",
  },
  {
    name: "Suriname",
    code: "SR",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â·",
    e164_country_code: "+597",
    slug: "suriname",
  },
  {
    name: "Svalbard & Jan Mayen",
    code: "SJ",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â¯",
    e164_country_code: "+047",
    slug: "svalbard-and-jan-mayen",
  },
  {
    name: "Sweden",
    code: "SE",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Âª",
    e164_country_code: "+046",
    slug: "sweden",
  },
  {
    name: "Switzerland",
    code: "CH",
    emoji: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â­",
    e164_country_code: "+041",
    slug: "switzerland",
  },
  {
    name: "Syria",
    code: "SY",
    emoji: "Ã°Å¸â€¡Â¸Ã°Å¸â€¡Â¾",
    e164_country_code: "+963",
    slug: "syria",
  },
  {
    name: "Taiwan",
    code: "TW",
    emoji: "Ã°Å¸â€¡Â¹Ã°Å¸â€¡Â¼",
    e164_country_code: "+886",
    slug: "taiwan",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    emoji: "Ã°Å¸â€¡Â¹Ã°Å¸â€¡Â¯",
    e164_country_code: "+992",
    slug: "tajikistan",
  },
  {
    name: "Tanzania",
    code: "TZ",
    emoji: "Ã°Å¸â€¡Â¹Ã°Å¸â€¡Â¿",
    e164_country_code: "+255",
    slug: "tanzania",
  },
  {
    name: "Thailand",
    code: "TH",
    emoji: "Ã°Å¸â€¡Â¹Ã°Å¸â€¡Â­",
    e164_country_code: "+066",
    slug: "thailand",
  },
  {
    name: "Timor-Leste",
    code: "TL",
    emoji: "Ã°Å¸â€¡Â¹Ã°Å¸â€¡Â±",
    e164_country_code: "+670",
    slug: "timor-leste",
  },
  {
    name: "Togo",
    code: "TG",
    emoji: "Ã°Å¸â€¡Â¹Ã°Å¸â€¡Â¬",
    e164_country_code: "+228",
    slug: "togo",
  },
  {
    name: "Tokelau",
    code: "TK",
    emoji: "Ã°Å¸â€¡Â¹Ã°Å¸â€¡Â°",
    e164_country_code: "+690",
    slug: "tokelau",
  },
  {
    name: "Tonga",
    code: "TO",
    emoji: "Ã°Å¸â€¡Â¹Ã°Å¸â€¡Â´",
    e164_country_code: "+676",
    slug: "tonga",
  },
  {
    name: "Trinidad & Tobago",
    code: "TT",
    emoji: "Ã°Å¸â€¡Â¹Ã°Å¸â€¡Â¹",
    e164_country_code: "+001",
    slug: "trinidad-and-tobago",
  },
  {
    name: "Tunisia",
    code: "TN",
    emoji: "Ã°Å¸â€¡Â¹Ã°Å¸â€¡Â³",
    e164_country_code: "+216",
    slug: "tunisia",
  },
  {
    name: "Turkey",
    code: "TR",
    emoji: "Ã°Å¸â€¡Â¹Ã°Å¸â€¡Â·",
    e164_country_code: "+090",
    slug: "turkey",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    emoji: "Ã°Å¸â€¡Â¹Ã°Å¸â€¡Â²",
    e164_country_code: "+993",
    slug: "turkmenistan",
  },
  {
    name: "Turks & Caicos Islands",
    code: "TC",
    emoji: "Ã°Å¸â€¡Â¹Ã°Å¸â€¡Â¨",
    e164_country_code: "+001",
    slug: "turks-and-caicos-islands",
  },
  {
    name: "Tuvalu",
    code: "TV",
    emoji: "Ã°Å¸â€¡Â¹Ã°Å¸â€¡Â»",
    e164_country_code: "+688",
    slug: "tuvalu",
  },
  {
    name: "Uganda",
    code: "UG",
    emoji: "Ã°Å¸â€¡ÂºÃ°Å¸â€¡Â¬",
    e164_country_code: "+256",
    slug: "uganda",
  },
  {
    name: "Ukraine",
    code: "UA",
    emoji: "Ã°Å¸â€¡ÂºÃ°Å¸â€¡Â¦",
    e164_country_code: "+380",
    slug: "ukraine",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    emoji: "Ã°Å¸â€¡Â¦Ã°Å¸â€¡Âª",
    e164_country_code: "+971",
    slug: "united-arab-emirates",
  },
  {
    name: "United Kingdom",
    code: "GB",
    emoji: "Ã°Å¸â€¡Â¬Ã°Å¸â€¡Â§",
    e164_country_code: "+044",
    slug: "united-kingdom",
  },
  {
    name: "Uruguay",
    code: "UY",
    emoji: "Ã°Å¸â€¡ÂºÃ°Å¸â€¡Â¾",
    e164_country_code: "+598",
    slug: "uruguay",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    emoji: "Ã°Å¸â€¡ÂºÃ°Å¸â€¡Â¿",
    e164_country_code: "+998",
    slug: "uzbekistan",
  },
  {
    name: "Vanuatu",
    code: "VU",
    emoji: "Ã°Å¸â€¡Â»Ã°Å¸â€¡Âº",
    e164_country_code: "+678",
    slug: "vanuatu",
  },
  {
    name: "Vatican City",
    code: "VA",
    emoji: "Ã°Å¸â€¡Â»Ã°Å¸â€¡Â¦",
    e164_country_code: "+379",
    slug: "vatican-city",
  },
  {
    name: "Venezuela",
    code: "VE",
    emoji: "Ã°Å¸â€¡Â»Ã°Å¸â€¡Âª",
    e164_country_code: "+058",
    slug: "venezuela",
  },
  {
    name: "Vietnam",
    code: "VN",
    emoji: "Ã°Å¸â€¡Â»Ã°Å¸â€¡Â³",
    e164_country_code: "+084",
    slug: "vietnam",
  },
  {
    name: "Wallis & Futuna",
    code: "WF",
    emoji: "Ã°Å¸â€¡Â¼Ã°Å¸â€¡Â«",
    e164_country_code: "+681",
    slug: "wallis-and-futuna",
  },
];
